---
name: CI
on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'development'
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} 
    GCP_REGION: ${{ secrets.GCP_REGION }}
    GCP_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
    GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json 
jobs:
    check-terraform-code:
        name: Check Terraform Code
        runs-on: ubuntu-latest
        environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: 1.8.1
            - name: Set up gcloud Cloud SDK environment
              uses: google-github-actions/setup-gcloud@v2.1.1
            - name: Authenticate to GCP
              run: |
                echo "${GCP_CREDENTIALS_JSON}" > ${{ github.workspace }}/credentials.json            
                gcloud auth activate-service-account --key-file=${{ github.workspace }}/credentials.json
                gcloud config set project ${{ env.GCP_PROJECT_ID }}  
            - name: Terraform Init
              run: terraform init
              working-directory: ./infra
            - name: Terraform Format
              run: terraform fmt -check
              working-directory: ./infra
            - name: Terraform Validate
              run: terraform validate
              working-directory: ./infra
            - name: Terraform Plan
              run: terraform plan
              working-directory: ./infra
              env:
                TF_VAR_environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
                TF_VAR_project_id: ${{ env.GCP_PROJECT_ID }}
                TF_VAR_region: ${{ env.GCP_REGION }}
    # check-python-code:
    #     name: Check Python Code
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v2
    #         - name: Setup Python
    #           uses: actions/setup-python@v2
    #           with:
    #               python-version: 3.9
    #         - name: Install dependencies
    #           run: pip install -r requirements.txt
    #         - name: Run tests
    #           run: pytest